; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 16 2021 01:51:37 GMT-0500 (Eastern Standard Time)
M561 ; clear any bed transform
G0 X60 Y60 Z10
G30 ; adjust z
G29 ; probe the bed and enable compensation
