; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 16 2021 01:51:37 GMT-0500 (Eastern Standard Time)
G91              ; relative positioning
; G1 H2 Z-5 F6000   ; lift Z relative to current position
G1 H1 Z137 F1800 ; move Z up until the endstop is triggered
G92 Z131         ; set Z position to axis maximum (you may want to adjust this)
G1 Z120          ; move Z to 120