; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 16 2021 01:51:37 GMT-0500 (Eastern Standard Time)
G91               ; relative positioning
G1 H1 Y-132 F1800 ; move quickly to Y axis endstop and stop there (first pass)
G1 H2 Y5 F6000    ; go back a few mm
G1 H1 Y-132 F360  ; move slowly to Y axis endstop once more (second pass)
G90               ; absolute positioning

