; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Thu Dec 16 2021 01:51:37 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P0

